[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 200

[theme]
base = "light"
primaryColor = "#1f77b4"

[runner]
magicEnabled = false
installTracer = false

[logger]
level = "info"